export DYLD_LIBRARY_PATH=/opt/intel/lib:/opt/intel/mkl/lib
export EDITOR=/usr/bin/vi
export HOMEBREW_GITHUB_API_TOKEN="$(cat ~/.zsh/homebrew_github_api_token)"
export LESS=-r
export LSCOLORS=ExFxBxDxCxegedabagacad
export PAGER=/usr/bin/less
# export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp
export TORCH_DATA_PATH=/Users/kat/torch/dp
export VISUAL='/usr/local/bin/atom --new-window --wait'
