export CUDA_HOME=/usr/local/cuda
export DYLD_LIBRARY_PATH=/opt/intel/lib:/opt/intel/mkl/lib:/usr/local/cuda/lib
export EDITOR=/usr/bin/vi
export HOMEBREW_GITHUB_API_TOKEN=d23f67077cbb2ea2a92ea301e36081539efd3f00
export LESS=-r
export LSCOLORS=ExFxBxDxCxegedabagacad
export NVBLAS_CONFIG_FILE=/Users/kat/.nvblas.conf
export PAGER=/usr/bin/less
# export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp
export TORCH_DATA_PATH=/Users/kat/Library/torch/dp/
export VISUAL='/usr/local/bin/atom --new-window --wait'
