export DYLD_LIBRARY_PATH="$HOME"/.local/lib:/opt/intel/lib:/opt/intel/mkl/lib
export HOMEBREW_GITHUB_API_TOKEN="$(cat ~/.zsh/homebrew_github_api_token)"
export LESS=-r
export LSCOLORS=ExFxBxDxCxegedabagacad
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES  # Fixes Python forking on macOS
export PAGER=/usr/bin/less
export PROMPT_TOOLKIT_COLOR_DEPTH=DEPTH_24_BIT
# export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp
# export TORCH_DATA_PATH=/Users/kat/torch/dp
export VISUAL='/usr/local/bin/atom --new-window --wait'
export EDITOR="$VISUAL"
